### ISSUE TITLE
Translate comments to English

### ISSUE THREAD

**Issue by Ghibranalj** [c-krit/ferox#10]
I know i might sound entitled. But it would be really nice if you can translate the comments (at least in the header file) to English.

**Comment by jdeokkim** [comment]
I appreciate your suggestion. I've been busy preparing for assignments and finals at my university these days so I will try to translate them to English as soon as I finish my exams! 

Meanwhile, you can check out the English documentation of this library here (with comments translated to English): https://github.com/c-krit/ferox/wiki
