### ISSUE TITLE
Starter template project with raylib

### ISSUE THREAD

**Issue by ghost** [c-krit/ferox#24]
Good day! Thank you for your work!
It will be great to have starter (game) template project with raylib.

Also are you going to publish it to https://packages.msys2.org?

**Comment by jdeokkim** [comment]
Hello, thank you for your interest in this project! To answer to your suggestions:

1. Yes, I'm planning to create a starter template for raylib and ferox when the v1.0.0 release is ready. This means I still have bugs to fix and features to implement.

2. I haven't thought about it yet, but I think it would be great for this project to be published to the MSYS package list when we get a stable release. 

I will create new issues related to your suggestions when the stable release is ready!
